[IN-1] Create an account providing e-mail and password
adamjorge/instamint pull request #10
Opened 2024-04-18 19:39 UTC by Prajay-Chaudhary

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-1

2024-04-19 10:13 UTC, adamjorge requested changes
Summary of the request changes:

- [x] Optimizations
- [x] More validations of fields that you're sending to the API
- [x] Usage of shadcn components lib

2024-04-19 10:13 UTC, adamjorge commented on package.json
> +    "fs": "^0.0.1-security",
I don't understand where you're using this package, his documentation looks weird:
https://www.npmjs.com/package/fs

2024-04-19 10:13 UTC, adamjorge commented on src/actions/auth.ts
> +    port: Number(process.env.EMAIL_PORT) || 0,
I wonder why you're not throwing an error if the env variable is not found instead of implementing the possibility of having port = 0

2024-04-19 10:13 UTC, adamjorge commented on src/components/custom/email/verify/verify-email.tsx
> +import Form from "./send/form"
Try to use alias import here since we decided we're always using it

2024-04-19 10:13 UTC, adamjorge commented on src/components/custom/email/verify/send/resend-button.tsx
I wonder why you're not using shadcn lib for your components we have it already installed and you're working on the main app

2024-04-19 10:13 UTC, adamjorge commented on src/components/custom/signup/form.tsx
> +            Already have an account?&nbsp;
Try to organize UI using tailwind CSS because this HTML fragment is not maintainable:

https://www.freecodecamp.org/news/tab-space-instead-of-multiple-non-breaking-spaces/

2024-04-19 10:13 UTC, adamjorge commented on src/providers/providers.tsx
> +      <SessionProvider>{children}</SessionProvider>
"If you are using the App Router, we encourage you to use [getServerSession](https://next-auth.js.org/configuration/nextjs#getserversession) in server contexts instead." 

If you find it easy to use getServerSession instead go for it, otherwise stay with the SessionProvider

2024-04-19 19:47 UTC, Prajay-Chaudhary commented on package.json
> +    "fs": "^0.0.1-security",
I was  trying to use the Winston logging library in a Next.js. 

Winston is primarily designed for server-side logging in Node.js environments and relies on features like the 'fs' module, which are not available in the browser.

Since we are not using it anymore, i've removed it.

2024-04-26 22:04 UTC, adamjorge commented
Feature can't build (27/04/2024)

2024-04-27 16:47 UTC, adamjorge reviewed
- [x]  Use the same schema as develop I'm getting this error with the current database because you changed the name of the fields: 

```The column `User.emailVerifiedAt` does not exist in the current database.```

- [x] Fix the linter warnings:

```
10:16  Warning: Function 'VerifyEmail' has too many lines (57). Maximum allowed is 50.  max-lines-per-function

29:6  Warning: React Hook useEffect has a missing dependency: 'emailVerification'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./src/components/custom/signup/form.tsx
35:16  Warning: Function 'SignUpForm' has too many lines (88). Maximum allowed is 50.  max-lines-per-function
```

- [x] Move all xxxxUtils files to a utils folder (and delete utils from there name) and remove auth.js since we already have that file and you're not using it

- [x]  Resolve conflicts with develop

2024-04-27 16:47 UTC, adamjorge commented on prisma/schema.prisma
> +  minterId        Int?
Try to use the prisma schema of develop there or we will have to change all the fields in queries that you changed there (eg: you renamed emailVerified to emailVerifiedAt)

Actual schema is: https://github.com/adammehdaoui/instamint/blob/develop/prisma/schema.prisma

2024-04-27 16:47 UTC, adamjorge commented on src/actions/auth.ts
We already have auth.ts to sign which is confusing (and you're not using it you're just rexporting your files)

2024-04-27 16:47 UTC, adamjorge commented on src/components/custom/email/verify/verify-email.tsx
> +  }, [email, token])
Missing dependency emailVerification

2024-04-30 20:34 UTC, Prajay-Chaudhary commented on prisma/schema.prisma
> +  minterId        Int?
Thanks for the comment. Now, it's maintained with develop branch.

2024-04-30 20:36 UTC, Prajay-Chaudhary commented on src/components/custom/email/verify/verify-email.tsx
> +  }, [email, token])
I've fixed this missing dependency warning.

2024-04-30 20:38 UTC, Prajay-Chaudhary commented on src/actions/auth.ts
Sorry for the confusion, i've deleted that file and the auth part for signup has been moved to the lib/utils folder.

2024-05-01 14:15 UTC, adamjorge approved these changes

2024-05-01 14:15 UTC, merged

2024-05-11 08:52 UTC, avetisk commented on prisma/migrations/20240416202843_add_user_table/migration.sql
> +    "emailVerifToken" VARCHAR(255),
Better use `text` type for tokens.

2024-05-11 08:52 UTC, avetisk commented on prisma/migrations/20240416202843_add_user_table/migration.sql
> +    "password" VARCHAR(255) NOT NULL,
Avoid confusion and call it `passwordHash`.

2024-05-11 08:53 UTC, avetisk commented on src/app/auth/email/verify/loading.tsx
> +    <>
Useless fragment.

2024-05-11 08:54 UTC, avetisk commented on src/components/custom/email/verify/form.tsx
> +    <>
Useless fragment.

2024-05-11 08:54 UTC, avetisk commented on src/components/custom/email/verify/form.tsx
> +  const verificationSent = Boolean(searchParams.get("verification_sent"))
Be sure to parse it properly as `=false` or `=0` may end up being casted to `true`.

2024-05-11 08:54 UTC, avetisk commented on src/components/custom/email/verify/use-email-verification.tsx
> +    if (userEmail && token) {
Use an early return.

2024-05-11 08:55 UTC, avetisk commented on src/components/custom/email/verify/use-email-verification.tsx
> +        .then(() => {
You're already using async/await style, why change it here?

2024-05-11 08:55 UTC, avetisk commented on src/components/custom/email/verify/verify-email.tsx
> +          <>
Useless fragment.

2024-05-11 08:55 UTC, avetisk commented on src/components/custom/email/verify/verify-email.tsx
> +              <div className="text-green-500">{errorMessage}</div>
Green color for an error? 🤔

2024-05-11 08:56 UTC, avetisk commented on src/components/custom/email/verify/verify-email.tsx
> +              <div className="text-green-500">{result}</div>
You should create reusable component.

e.g `SuccessMessage`, `ErrorMessage`, etc.

2024-05-11 08:57 UTC, avetisk commented on src/app/auth/email/verify/loading.tsx
> +      </div>
Is this a ChatGPT/copilote code?

Because you have declared nowhere in your code the CSS class `loading-spinner`.

2024-05-14 17:32 UTC, adamjorge commented on prisma/migrations/20240416202843_add_user_table/migration.sql
> +    "emailVerifToken" VARCHAR(255),
Resolved in this PR: https://github.com/adammehdaoui/instamint/pull/24

2024-05-14 17:33 UTC, adamjorge commented on src/app/auth/email/verify/loading.tsx
> +    <>
Resolved in this PR: https://github.com/adammehdaoui/instamint/pull/24

2024-05-14 17:34 UTC, adamjorge commented on src/app/auth/email/verify/loading.tsx
> +      </div>
Resolved in this PR by @Prajay-Chaudhary: https://github.com/adammehdaoui/instamint/pull/24

2024-05-14 17:35 UTC, adamjorge commented on src/components/custom/email/verify/verify-email.tsx
> +              <div className="text-green-500">{result}</div>
Resolved in this PR by @Prajay-Chaudhary: https://github.com/adammehdaoui/instamint/pull/24

2024-05-14 17:35 UTC, adamjorge commented on src/components/custom/email/verify/verify-email.tsx
> +              <div className="text-green-500">{errorMessage}</div>
Resolved in this PR by @Prajay-Chaudhary: https://github.com/adammehdaoui/instamint/pull/24

2024-05-14 17:40 UTC, adamjorge commented on src/components/custom/email/verify/form.tsx
> +  const verificationSent = Boolean(searchParams.get("verification_sent"))
Resolved in this PR by @Prajay-Chaudhary: https://github.com/adammehdaoui/instamint/pull/24

2024-05-14 17:41 UTC, adamjorge commented on src/components/custom/email/verify/form.tsx
> +    <>
Resolved in this PR by @Prajay-Chaudhary: https://github.com/adammehdaoui/instamint/pull/24

2024-05-14 17:52 UTC, adamjorge commented on src/components/custom/email/verify/use-email-verification.tsx
> +        .then(() => {
Resolved in this PR by @Prajay-Chaudhary: https://github.com/adammehdaoui/instamint/pull/24

2024-05-14 17:53 UTC, adamjorge commented on src/components/custom/email/verify/use-email-verification.tsx
> +    if (userEmail && token) {
Resolved in this PR by @Prajay-Chaudhary: https://github.com/adammehdaoui/instamint/pull/24