[IN-22] Change app interface language
adamjorge/instamint pull request #12
Opened 2024-04-19 13:07 UTC by adamjorge

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-22

Summary of the PR:

- Handling app language using next-intl i18n lib (ICU compatible)
- Refacto of providers
- Segmentation of the admin layout and the main app layout logic
- Translation in 6 languages made using i18n nexus

2024-04-19 17:57 UTC, jimmy-martin requested changes

2024-04-19 17:57 UTC, jimmy-martin commented on src/app/[locale]/search/page.tsx
> +        <p>Search</p>
maybe you forgot to translate here ?

2024-04-19 18:00 UTC, jimmy-martin reviewed
Update tests too

2024-04-19 19:31 UTC, adamjorge commented on src/app/[locale]/search/page.tsx
> +        <p>Search</p>
Yes, changed the locales json structure to translate here

2024-04-20 06:28 UTC, jimmy-martin requested changes

2024-04-20 06:28 UTC, jimmy-martin commented on src/app/[locale]/search/loading.tsx
> +  return <div className="text-center">{t("loading")}</div>
you have to load "global" to reach `t("loading")`

2024-04-20 14:57 UTC, jimmy-martin approved these changes

2024-04-20 14:57 UTC, merged

2024-05-11 19:07 UTC, avetisk commented on src/components/custom/minters/minter-list.tsx
>      <div className="my-1">
Margins should be affected from outside.

Also, you should always forward `className` prop to the outermost element of your component (which will allow to apply margins for instance).