[IN-84] Search users or TEA BAGS (location and price range)
adamjorge/instamint pull request #13
Opened 2024-04-21 11:02 UTC by jimmy-martin

NB: This PR is the continuation of the first search [PR](https://github.com/adammehdaoui/instamint/pull/9), which lacked search by location and price range.

Linked to this ticket : https://instamint-deva.atlassian.net/browse/IN-84
Last search ticket : https://instamint-deva.atlassian.net/browse/IN-28

2024-04-21 15:23 UTC, Prajay-Chaudhary requested changes
**Summary of Requested Changes:**

- [x] UX/UI

Overall, the changes in this pull request are looking good, but I have some feedback regarding the UI/UX:

1. Clear/X icon in the search bar/form field to clear the nputs is not functioning as expected. It should clear when clicked. This is important for usability and user experience.

2. Resetting form data on Cancel button click or modal close: After clicking on the Cancel button or when the user clicks outside the search modal, all user-entered data should be cleared. This ensures a clean and intuitive experience for the user.

Thanks.

2024-04-21 15:23 UTC, Prajay-Chaudhary commented on src/components/ui/label.tsx
There should be no blank line between imports, i.e remove the line before " import { cn } from "@/lib/utils" ".

2024-04-21 15:40 UTC, jimmy-martin commented on src/components/ui/label.tsx
Since we're going to use a plugin that will take care of arranging the imports correctly, we won't attach too much importance to this here. Furthermore, it's possible to have spaces between imports, and we're going to use a well-known trivago plugin used by the React community, which will create spaces to separate imports correctly.

See : https://github.com/adammehdaoui/instamint/pull/17

2024-04-21 20:19 UTC, Prajay-Chaudhary approved these changes

2024-04-21 20:22 UTC, merged

2024-05-18 15:56 UTC, avetisk commented on src/components/custom/search/drawer/search-drawer.tsx
>  export default function SearchDrawer({ ...props }: SearchDrawerProps) {
Why do you spread if you're taking the same content from the object???

2024-05-18 15:59 UTC, avetisk commented on src/lib/query/search/search-url-builder.ts
> +  }
You're just remapping kind of uselessly URLSearchParams...