[IN-33] Fold & unfold comments thread
adamjorge/instamint pull request #14
Opened 2024-04-25 08:58 UTC by jimmy-martin

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-33

2024-04-29 09:02 UTC, adamjorge commented
Assigned myself as a reviewer to the PR since no one took it after 4 days.

2024-04-29 09:26 UTC, adamjorge requested changes
**!!! THIS ERROR IS OUTDATED AFTER THE LAST COMMIT !!!**

I have this error when trying your code with the current database:

```
Invalid `prisma.minter.findMany()` invocation:
The column `Minter.isAdmin` does not exist in the current database.
```

Try to pull the most recent prisma schema from develop.

2024-04-29 09:26 UTC, adamjorge commented on src/components/custom/comment-section/child-comment.tsx
> +        <AvatarImage alt="User Avatar" src="/flags/en.svg" />
Enhancement: pass the user profile picture here so we will only need to have a valid one here in the future.
Seed with this API for example: https://randomuser.me/

2024-04-29 09:26 UTC, adamjorge commented on src/components/custom/comment-section/comment.tsx
> +          <AvatarImage alt="User Avatar" src="/flags/en.svg" />
Same here, try to use real pfp link so the feature of displaying it is already done

2024-04-29 19:53 UTC, adamjorge approved these changes

2024-04-29 19:57 UTC, adamjorge approved these changes
Unit tests will be updated for this user story in another PR:
https://instamint-deva.atlassian.net/browse/IN-34

2024-04-29 19:58 UTC, merged

2024-05-18 16:01 UTC, avetisk commented on prisma/scripts/nft/create-nfts.ts
> +  return await Promise.all(promises)
Useless if you're not gonna try/catch.

2024-05-18 16:02 UTC, avetisk commented on prisma/scripts/nft/create-nfts.ts
> +  const promises = data.map((nft) => prisma.nft.create({ data: nft }))
Why not using `createMany`.

2024-05-18 16:03 UTC, avetisk commented on src/components/custom/comment-section/child-comment.tsx
> +        <AvatarImage alt={comment.author.id.toString()} src={comment.author.avatarUrl} />
Useless info for `alt`: it's supposed to help the blind people...ID won't.

2024-05-18 16:04 UTC, avetisk commented on src/components/custom/comment-section/comment-section.tsx
> +    return <div>Loading...</div>
Maybe it's time to invest into a `Loader` component?

2024-05-18 16:04 UTC, avetisk commented on src/components/custom/comment-section/comment-section.tsx
> +    return <div>Error {error.message}</div>
Make an `ErrorMessage` component?

2024-05-18 16:05 UTC, avetisk commented on src/components/custom/comment-section/comment.tsx
> +          </h4>
h4? Why h4? Why not h3? 

You should use `article` and proper levels of heading within as it resets order of headings.

2024-05-18 16:06 UTC, avetisk commented on src/lib/query/nfts/fetchNftComments.ts
> +    const response = await axios.get(`/api/nfts/${nftId.toString()}/comments`)
You should really use a custom client and not "raw" axios client.

2024-05-18 16:06 UTC, avetisk commented on src/lib/query/nfts/fetchNftComments.ts
> +    }
Useless. You're not doing any error handling with this.

2024-05-18 16:06 UTC, avetisk commented on src/lib/query/nfts/validate-request.ts
> +}
??????????

2024-05-18 16:08 UTC, avetisk commented on src/validators/schemas/nfts/nftSchema.ts
> +})
You should use field validators instead of mashedup entity validators as they won't fit every need.

2024-05-18 16:37 UTC, adamjorge commented on src/components/custom/comment-section/comment-section.tsx
> +    return <div>Loading...</div>
Resolved in this PR: https://github.com/adammehdaoui/instamint/pull/25