[IN-83] Login to app as an admin (main app and backoffice)
adamjorge/instamint pull request #16
Opened 2024-04-26 08:17 UTC by adamjorge

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-83

2024-04-26 09:15 UTC, jimmy-martin requested changes

2024-04-26 09:15 UTC, jimmy-martin commented on .env.example
> +DATABASE_URL=""
You can pre-fill `DATABASE_URL` with the basic connection string as it will be easier to modify it afterwards

2024-04-26 09:15 UTC, jimmy-martin commented on prisma/schema.prisma
> +  Minter        Minter    @relation(fields: [minterId], references: [id])
use lowercase instead : 
`minter Minter @relation(fields: [minterId], references: [id])`

2024-04-26 09:15 UTC, jimmy-martin commented on prisma/schema.prisma
> +  User                User[]
Same here, you can use lowercase and dont forget to use plural (update all the prisma schema if you can as we saw together): 

```
comments             Comment[]
originalContents     OriginalContent[]
reports              Report[]
users                User[]
```

2024-04-26 09:15 UTC, jimmy-martin commented on src/app/[locale]/layout.tsx
> +                  Sign out
you can add a translation for "Sign out"

2024-04-26 09:15 UTC, jimmy-martin commented on src/lib/auth.ts
Is it better to use eslint disabling rules on the entire file instead of multiplying `// eslint-disable-next-line new-cap` ?

2024-04-26 09:15 UTC, jimmy-martin commented on src/lib/db.ts
> +const prisma = global.prismaGlobal ?? prismaSingleton()
Why this change ?

2024-04-26 09:15 UTC, jimmy-martin commented on src/lib/db.ts
> -if (process.env.NODE_ENV !== "production" && !global.prismaGlobal) {
Why this change ? It was here to avoid to set global.prismaGlobal = prisma when it's already set.

2024-04-26 09:15 UTC, jimmy-martin commented on src/lib/query/minters/search.ts
> -      isAdmin: false,
do you want to list admins on search ?

2024-04-26 10:09 UTC, adamjorge commented on src/lib/db.ts
> +const prisma = global.prismaGlobal ?? prismaSingleton()
Same use case, I just took it from the official docs because I tried other confs:

https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices

2024-04-26 10:10 UTC, adamjorge commented on src/lib/db.ts
> -if (process.env.NODE_ENV !== "production" && !global.prismaGlobal) {
Same use case, I just took it from the official docs because I tried other confs:

https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices

2024-04-26 10:13 UTC, adamjorge commented on src/lib/query/minters/search.ts
> -      isAdmin: false,
An admin is also considered as a Minter in our app but we can talk about that.
I you really want to not list admin, it means that the search query needs a join query to access isAdmin in User (changed Minter.isAdmin => User.isAdmin)

2024-04-26 16:44 UTC, adamjorge commented on src/lib/auth.ts
I can change that, it was just to show that i'm respecting linter practices for the rest of the file

2024-04-27 15:39 UTC, jimmy-martin approved these changes

2024-04-27 15:40 UTC, merged

2024-05-11 19:08 UTC, avetisk commented on prisma/schema.prisma
> +  user         User     @relation(fields: [userId], references: [id])
Not a good idea to handle sessions in a SQL database.

It's not scalable.

2024-05-11 19:09 UTC, avetisk commented on prisma/schema.prisma
> +
Just use JWT or even better PASETO token for this.

You can always keep in a KV in memory stores those tokens if you want to double validate them to ensure single usage.

2024-05-11 19:10 UTC, avetisk commented on src/app/[locale]/(portal)/layout.tsx
> +      >
Server Action === PHP === 🙅‍♂️

2024-05-11 19:11 UTC, avetisk commented on src/app/[locale]/(portal)/page.tsx
> +  return <></>
Just return `null` 🤣

2024-05-11 19:12 UTC, avetisk commented on src/lib/auth.ts
> +    signIn: "/en/login"
What about i18n?

2024-05-13 10:25 UTC, adamjorge commented on src/lib/auth.ts
> +    signIn: "/en/login"
Changes made in this PR: https://github.com/adammehdaoui/instamint/pull/18
("/en/login" => "/login")

2024-05-24 16:26 UTC, adamjorge commented on src/app/[locale]/(portal)/page.tsx
> +  return <></>
Updated with the feed of the minter in this PR: https://github.com/adammehdaoui/instamint/pull/25