[IN-85] Install a plugin to sort imports
adamjorge/instamint pull request #17
Opened 2024-05-01 17:03 UTC by jimmy-martin

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-85

2024-05-01 22:06 UTC, adamjorge requested changes

2024-05-01 22:06 UTC, adamjorge commented on src/components/ui/custom/LinkButton.tsx
Change the name of the file to kebab-case

2024-05-02 14:43 UTC, adamjorge approved these changes

2024-05-02 14:44 UTC, merged

2024-06-02 17:32 UTC, avetisk commented on src/components/ui/custom/link-button.tsx
> +}
```ts
  const Component = withLocale ? LocaleLink : DefaultLink

  return (
    <LocaleLink href={href} passHref>
      <Button className={className} {...props}>
        {children}
      </Button>
    </LocaleLink>
  )
```