[IN-5] Delete personal account as a MINTER
adamjorge/instamint pull request #18
Opened 2024-05-04 15:18 UTC by adamjorge

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-5

**Includes daily cron job to delete all marked users**

Workflow for deleting an account:

- The minter confirms his desire to delete his account and is then redirected to the login page.
- The 'deletedAt' field is populated with today’s date.
- When the cron job executes, the minter’s data is deleted from the database (from both the Minter and User tables; additional tables can be included in this branch).

Also, the cron job can be tested using postman to call the API but can't be tested in dev env like a real cron because Vercel only accept them on prod using free plan.

2024-05-05 00:08 UTC, Prajay-Chaudhary requested changes
- [x] Try to have the develop branch current changes and resolve the conflicts.

- [x] Maintain folder structures.

2024-05-05 00:08 UTC, Prajay-Chaudhary commented on prisma/schema.prisma
I don't understand why you made Minter and minterId optional fields for Comment model. Because comments are created by minter, no? Could you please explain the reason?.

2024-05-05 00:08 UTC, Prajay-Chaudhary commented on src/app/api/users/daily/route.ts
What does daily folder means?. Same question for the folder under :[src/lib/query/minters/daily/delete.ts].

2024-05-05 08:07 UTC, adamjorge commented on prisma/schema.prisma
Because when you delete a Minter the relation doesn't exist anymore.
Like I said here I can add additionnal tables:
*from both the Minter and User tables; additional tables can be included in this branch*

2024-05-05 08:08 UTC, adamjorge commented on src/app/api/users/daily/route.ts
It's the cron job that will be executed everyday (daily)

2024-05-05 17:47 UTC, Prajay-Chaudhary commented on prisma/schema.prisma
Okay, I understood the context of these changes.

2024-05-05 17:49 UTC, Prajay-Chaudhary commented on src/app/api/users/daily/route.ts
Thanks for the changes you made afterwards.

2024-05-05 18:03 UTC, Prajay-Chaudhary approved these changes

2024-05-05 18:04 UTC, merged

2024-05-11 19:14 UTC, avetisk commented on prisma/schema.prisma
> +  author    Minter?   @relation(fields: [authorId], references: [id])
How can a comment be without an author? 🤔

2024-05-11 19:14 UTC, avetisk commented on prisma/schema.prisma
> +  author    Minter?   @relation(fields: [authorId], references: [id])
You need to be smarter here ;)

2024-05-11 19:15 UTC, avetisk commented on src/app/api/users/[id]/route.ts
> +    )
You should use a wrapper to avoid doing this everytime.

2024-05-11 19:16 UTC, avetisk commented on src/lib/query/minters/clean.ts
> +  }
Why you're not using `.map()`?

2024-05-11 19:16 UTC, avetisk commented on src/lib/query/minters/clean.ts
> +  })
`.map()`.

2024-05-24 16:28 UTC, adamjorge commented on prisma/schema.prisma
> +  author    Minter?   @relation(fields: [authorId], references: [id])
We wanted to keep the comment even if the minter delete his account, front will displays "deleted user" in this case