[IN-102] Refactor on feature to create an account as a minter with new changes
adamjorge/instamint pull request #24
Opened 2024-05-12 13:31 UTC by Prajay-Chaudhary

"Here, I've implemented the changes to the signup feature based on the feedback received from the professor."

- Updated the user model schema.
- Removed unnecessary fragments.
- Refactored the code for improved readability and maintainability.
- Implemented internationalization (i18n) comprehensively throughout the feature.

2024-05-13 10:19 UTC, adamjorge requested changes

2024-05-13 10:19 UTC, adamjorge commented on src/components/custom/email/verify/use-email-verification.tsx
> -          setErrorMessage("Error occured")
You didn't switch to await as the review said ? Is it not possible ?

2024-05-13 20:53 UTC, Prajay-Chaudhary commented on src/components/custom/email/verify/use-email-verification.tsx
> -          setErrorMessage("Error occured")
Yes, it's possible to use await there. Could you now check it to see if that's acceptable to you?

2024-05-14 17:30 UTC, adamjorge approved these changes

2024-05-14 17:51 UTC, adamjorge requested changes

2024-05-14 17:51 UTC, adamjorge commented on src/components/custom/email/verify/verify-email.tsx
> +        <>
I think this react fragment is still useless, you're wrapping a div to avoid the "Do not nest ternary expressions" warning. 
Maybe move that logic in a dedicated component? 

Referencing this review: https://github.com/adammehdaoui/instamint/pull/10#discussion_r1597404499

2024-05-14 20:30 UTC, adamjorge approved these changes

2024-05-14 20:30 UTC, Prajay-Chaudhary commented on src/components/custom/email/verify/verify-email.tsx
> +        <>
Yes, you're correct. So, now i've moved the entire logic to a seperate component.

2024-05-14 20:35 UTC, merged

2024-06-07 09:53 UTC, avetisk commented on src/components/custom/email/verify/form.tsx
> +    <div>
Useless div.