[IN-37] Follow a MINTER (and see his content in my feed)
adamjorge/instamint pull request #25
Opened 2024-05-12 22:05 UTC by adamjorge

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-37

The feature lacks the management of private profiles as the profile viewing is not yet developed.
I will do a ticket later for this use case.

2024-05-14 14:22 UTC, jimmy-martin requested changes

2024-05-14 14:22 UTC, jimmy-martin commented on src/app/[locale]/(portal)/layout.tsx
> +          }}
try to not use server action

2024-05-14 14:22 UTC, jimmy-martin commented on src/app/[locale]/(portal)/page.tsx
> +  const minterId = currentUser.minter.id
useless variable here

2024-05-14 14:22 UTC, jimmy-martin commented on src/app/[locale]/(portal)/search/page.tsx
> +    redirect("/login")
we can't search if not logged in ?

2024-05-14 14:22 UTC, jimmy-martin commented on src/app/api/search/[type]/route.ts
> +  const currentUserId = userId as string
why use temporary variable instead of setting search or userId to `""` if null ?

```ts
const search = searchParams.get("search") || ""
// ...
const userId = searchParams.get("currentUserId") || ""
```

2024-05-14 14:22 UTC, jimmy-martin commented on src/components/custom/minters/minter-list.tsx
why pass the session object threw all these components ? Is it recoverable directly from the component that is using it ?

2024-05-14 14:22 UTC, jimmy-martin commented on src/components/custom/minters/minter-wrapper.tsx
maybe you can get the session here directly

2024-05-14 14:22 UTC, jimmy-martin commented on src/components/custom/search/search-results.tsx
same as above, why pass the session object threw all these components ? Is it recoverable directly from the component that is using it ?

2024-05-14 14:22 UTC, jimmy-martin commented on src/lib/query/search/search.ts
> +      return await searchMinters(searchTerm, currentUserId)
if we can search without being logged in we should not throw an error if currentUserId is null, if not its ok

2024-05-14 14:22 UTC, jimmy-martin commented on src/app/api/minters/follow/route.ts
> +  const { followerId, followingId } = data
you can destructure earlier

```ts
const { followerId, followingId } = (await req.json()) as Payload
```

2024-05-14 14:22 UTC, jimmy-martin commented on src/app/api/minters/follow/route.ts
> +  const { followerId, followingId } = dataToDelete
same here, you can destructure earlier :

```ts
const { followerId, followingId } = (await req.json()) as Payload
```

2024-05-14 14:22 UTC, jimmy-martin commented on src/app/api/minters/follow/route.ts
> +    return Response.json({ followResponse })
is the followResponse property useful on the response ?

In the project we usually do it this way :

 ```ts
return Response.json(followResponse)
```

Is there a reason for the difference here ?

2024-05-14 14:22 UTC, jimmy-martin commented on src/components/custom/nfts/nft-card.tsx
> +export default function NftCard(nft: NftSearchNftSchemaType) {
Why rename the component as it is specific to the search page, and the one you created for the feed is a custom nft card too ? 
Maybe use a generic nft card ? 
If not maybe it's better to let the name as it was just maybe use the same wording as your new component (NftFeedCard) : `NftSearchCard` instead of `SearchNftCard` (previous version)

2024-05-14 14:22 UTC, jimmy-martin commented on src/components/custom/nfts/nft-list.tsx
> +export default function NftList({ nfts }: NftListProps) {
Same as above try to find a good way to name it according to what you are doing for the NftCard

2024-05-14 14:22 UTC, jimmy-martin commented on src/lib/query/nfts/followNftsFeed.ts
maybe you can refactor/mutualize at least the select, skip, take with the `nftsFeed` function (src/lib/query/nfts/nftsFeed.ts)

2024-05-14 17:58 UTC, adamjorge commented on src/app/[locale]/(portal)/search/page.tsx
> +    redirect("/login")
As any typical social network app, you can't use it when you're not connected.

2024-05-14 18:08 UTC, adamjorge commented on src/app/api/search/[type]/route.ts
> +  const currentUserId = userId as string
To explicitly show to typescript that these parameters should NOT be null or `""`
It's tested in this function `checkSearchParams` before but typescript doesn't understand it because I'm returning error message when StatusCode.OK ==! checkResponse.status
In my opinion it's one of the rare case where you can use `as` but maybe it's a bad pattern

2024-05-14 18:12 UTC, adamjorge commented on src/components/custom/minters/minter-list.tsx
We don't have a Session Provider, we can't do it for now but I can try to implement it later

2024-05-14 18:12 UTC, adamjorge commented on src/components/custom/minters/minter-wrapper.tsx
We don't have a Session Provider, we can't do it for now but I can try to implement it later

2024-05-14 18:12 UTC, adamjorge commented on src/components/custom/search/search-results.tsx
We don't have a Session Provider, we can't do it for now but I can try to implement it later

2024-05-14 18:14 UTC, adamjorge commented on src/lib/query/search/search.ts
> +      return await searchMinters(searchTerm, currentUserId)
https://github.com/adammehdaoui/instamint/pull/25#discussion_r1600445356

2024-05-14 18:17 UTC, adamjorge commented on src/app/api/minters/follow/route.ts
> +  const { followerId, followingId } = dataToDelete
I'm changing that, in my opinion we don't understand the data we're manipulating when reading code but seems ok to me

2024-05-14 18:18 UTC, adamjorge commented on src/app/api/minters/follow/route.ts
> +    return Response.json({ followResponse })
I'm changing that, my bad 😝

2024-05-14 18:22 UTC, adamjorge commented on src/components/custom/nfts/nft-card.tsx
> +export default function NftCard(nft: NftSearchNftSchemaType) {
I renamed it to have the same syntax for all the search items.
e.g, tea-bag search item is not `TeaBagSearchCard`
If you wan't to keep that search in the name, I might also change the name of `MinterCard` and `TeaBagCard` since they're only used in the search use case

2024-05-14 18:23 UTC, adamjorge commented on src/components/custom/nfts/nft-list.tsx
> +export default function NftList({ nfts }: NftListProps) {
Same as here: https://github.com/adammehdaoui/instamint/pull/25#discussion_r1600470197

2024-05-14 18:40 UTC, adamjorge commented on src/app/[locale]/(portal)/layout.tsx
> +          }}
I think it's not linked to that PR because it's here since this: https://github.com/adammehdaoui/instamint/pull/16
Will do a enhancement ticket later.

2024-05-14 20:01 UTC, jimmy-martin commented on src/components/custom/nfts/nft-card.tsx
> +export default function NftCard(nft: NftSearchNftSchemaType) {
Ok, I think it's better to rename to this:

`TeaBagCard` to `TeaBagSearchCard` 
`MinterCard` to `MinterSearchCard`
`NftCard` to `NftSearchCard`

2024-05-14 20:02 UTC, jimmy-martin commented on src/components/custom/nfts/nft-list.tsx
> +export default function NftList({ nfts }: NftListProps) {
Try to rename as above to `NftSearchList`

2024-05-14 20:08 UTC, jimmy-martin commented on src/app/api/search/[type]/route.ts
> +  const currentUserId = userId as string
Ok but you can do it without using temporary variable (and maybe group them to indicate the difference with the optional searchParams) : 

```ts
const search = searchParams.get("search") as string
const userId = searchParams.get("currentUserId") as string
const minPrice = searchParams.get("min") || ""
const maxPrice = searchParams.get("max") || ""
```

2024-05-14 20:34 UTC, adamjorge commented on src/app/api/search/[type]/route.ts
> +  const currentUserId = userId as string
I can do that but when you read this code it just means it's a string, you can't understand that these variables can be undefined
If it's okay for you I push this

2024-05-14 21:14 UTC, jimmy-martin commented on src/app/api/search/[type]/route.ts
> +  const currentUserId = userId as string
We can merge like this but don't forget to create a ticket to improve this later

2024-05-15 08:18 UTC, jimmy-martin approved these changes

2024-05-15 08:19 UTC, merged

2024-06-07 07:52 UTC, avetisk commented on locales/es.json
> +    "deletedAccount": "Tu solicitud para eliminar tu cuenta ha sido recibida exitosamente. ¡Hasta pronto!"
You shouldn't translate keys that are already translated.

2024-06-07 07:53 UTC, avetisk commented on prisma/schema.prisma
> +  @@id(name: "followId", [followerId, followingId])
Add timestamps.

2024-06-07 08:11 UTC, avetisk commented on src/app/[locale]/(portal)/layout.tsx
> +          }}
🙅‍♂️

2024-06-07 08:27 UTC, avetisk commented on src/lib/query/minters/follow.ts
> +  }
```ts
  if (!user?.minterId) {
    throw new PublicErrorNotFound()
  }

  // somewhere else
  class PublicErrorNotFound extends PublicError {
    code = HTTP_ERRORS.NOT_FOUND

    constructor() {
      super("errors:api.notFound")
    }
  }
```

2024-06-07 08:29 UTC, avetisk commented on src/components/custom/feed/feed.tsx
> +    return <div className="text-center">{t("error")}</div>
`ErrorMessage`.

2024-06-07 08:30 UTC, avetisk commented on src/components/custom/minters/minter-wrapper.tsx
> +    }
Early return~!