[IN-4] Reset password as a MINTER through email verification
adamjorge/instamint pull request #26
Opened 2024-05-17 00:10 UTC by Prajay-Chaudhary

This is the feature where minter can securely reset their password by sending reset link to their registered email.

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-4

2024-05-20 12:31 UTC, adamjorge requested changes

2024-05-20 12:31 UTC, adamjorge commented on src/app/[locale]/(auth)/reset-password/page.tsx
You're not using any client feature here, mark it Form component

2024-05-20 12:31 UTC, adamjorge commented on src/app/[locale]/(auth)/update-password/page.tsx
You're not using any client feature here, mark it as a client component in the Form one or his child

2024-05-20 12:31 UTC, adamjorge commented on src/app/api/auth/update-password/route.ts
> +  newPassword: z.string().min(6).max(255),
Move this to the validator folder

2024-05-20 12:31 UTC, adamjorge commented on src/app/api/auth/update-password/route.ts
> +  const result = updatePasswordSchema.safeParse(formData)
Use zod refine in your Form: 
https://zod.dev/?id=refine

And don't write this function directly in the route file

2024-05-20 12:31 UTC, adamjorge commented on src/app/api/auth/update-password/route.ts
> +    throw new Error("User not found or invalid token")
Don't write this function directly in the route file

2024-05-20 12:31 UTC, adamjorge commented on src/app/api/auth/update-password/route.ts
> +      password: hashedPassword,
Don't write this function directly in the route file

2024-05-20 12:31 UTC, adamjorge commented on src/app/api/auth/update-password/route.ts
> +      return {
Don't write this function directly in the route file

2024-05-20 12:31 UTC, adamjorge commented on src/app/api/auth/update-password/route.ts
> +      { message: "Password updated successfully" },
Just use Response here

2024-05-20 12:31 UTC, adamjorge commented on src/components/custom/reset-password/reset-password-page.tsx
> +import * as z from "zod"
Why you're not importing this like:
`import { z } from "zod"`

2024-05-20 12:31 UTC, adamjorge commented on src/components/custom/reset-password/update-password/form-schema.tsx
Same as before why just not `import { z }`

2024-05-20 12:31 UTC, adamjorge commented on src/components/custom/reset-password/update-password/handle-submit.tsx
> +    toast.success("Password updated successfully")
no i18n ?

2024-05-20 12:31 UTC, adamjorge commented on src/components/custom/reset-password/update-password/update-password-form.tsx
> +    <main className="flex min-h-screen flex-col items-center justify-between p-24">
Why main again?

2024-05-20 12:31 UTC, adamjorge commented on src/components/custom/reset-password/update-password/update-password-page.tsx
You're not using any client feature here + you're using main fragment but layout already contains main you're doing:

`<main><main></main></main>`

2024-05-20 12:31 UTC, adamjorge commented on src/lib/utils/email.ts
> +      <p>Best Regards,</p>
We should start having i18n here

2024-05-20 12:31 UTC, adamjorge commented on src/lib/utils/reset-password/passwordResetService.ts
> +"use server"
https://github.com/adammehdaoui/instamint/pull/16#discussion_r1597494553 
With a little connection action, imagine using server action with a whole db connection.
I will not block the PR with that since you already dev all of that using server action

2024-05-20 12:31 UTC, adamjorge commented on src/lib/utils/reset-password/sendEmail.ts
> +"use server"
https://github.com/adammehdaoui/instamint/pull/16#discussion_r1597494553 
With a little connection action, imagine using server action with a whole db connection.
I will not block the PR with that since you already dev all of that using server action

2024-05-20 14:28 UTC, Prajay-Chaudhary commented on src/app/[locale]/(auth)/reset-password/page.tsx
So, you're saying that i don't need to use "use client" directive here?

2024-05-20 14:46 UTC, adamjorge commented on src/app/[locale]/(auth)/reset-password/page.tsx
Yes but maybe you'll need it in a child component

2024-05-21 07:30 UTC, adamjorge requested changes

2024-05-21 07:30 UTC, adamjorge commented on src/components/custom/reset-password/reset-password-page.tsx
> +  email: z
Move this to the validator folder

2024-05-21 07:30 UTC, adamjorge commented on src/components/custom/reset-password/reset-password-page.tsx
> +    <main className="flex min-h-screen flex-col items-center justify-between p-24">
Main in main here again

2024-05-21 07:30 UTC, adamjorge commented on src/components/custom/reset-password/update-password/update-password-page.tsx
> +"use client"
You're not using any client feature here

2024-05-21 10:10 UTC, adamjorge requested changes

2024-05-21 10:10 UTC, adamjorge commented on src/components/custom/reset-password/update-password/update-password-page.tsx
> +      <UpdatePasswordForm />
Useless div fragment

2024-05-21 19:03 UTC, adamjorge approved these changes

2024-05-21 19:03 UTC, merged

2024-06-07 09:54 UTC, avetisk commented on src/app/[locale]/(auth)/reset-password/page.tsx
> +}
Don't move all the content into a component!

2024-06-07 09:59 UTC, avetisk commented on src/components/custom/reset-password/update-password/update-password-form.tsx
> +        >
Make a component.

2024-06-07 10:00 UTC, avetisk commented on src/lib/utils/email.ts
>    const url = process.env.BASE_URL || "http://localhost:3000"
NEVER EVER keep hard coded values for ports, urls, etc.

2024-06-07 10:01 UTC, avetisk commented on src/lib/utils/email.ts
>    const url = process.env.BASE_URL || "http://localhost:3000"
Always use those values from a config file with validation.

https://github.com/nine1000school/asi-3-24-b_api/blob/main/src/web/config.js