[IN-19] Enable search by email
adamjorge/instamint pull request #29
Opened 2024-05-24 09:12 UTC by jimmy-martin

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-19

2024-05-27 13:13 UTC, adamjorge requested changes

2024-05-27 13:13 UTC, adamjorge commented on src/lib/query/minters/fetchToggleSearchability.ts
> +    const response = await axios.put(`/api/minters/${userId.toString()}/toggle-searchability`)
Put => Patch?

2024-05-27 13:13 UTC, adamjorge commented on src/lib/query/minters/fetchMinter.ts
> +    const response = await axios.get<Minter>(`/api/minters/${userId.toString()}`)
We're giving up API validation with zod then?

2024-05-27 13:13 UTC, adamjorge commented on src/lib/query/minters/fetchMinter.ts
> +    throw new Error(error as string)
A little bit too late because refacto PR is already merged but just: `throw error` then?

2024-05-27 13:13 UTC, adamjorge commented on src/app/api/minters/[id]/route.ts
> +  const minter = await prisma.minter.findFirstOrThrow({ where: { id: Number(id) } })
Move it to queries folder since we only have prisma queries in there

2024-05-27 13:13 UTC, adamjorge commented on src/lib/query/minters/fetchToggleSearchability.ts
> +    throw new Error(error as string)
A little bit too late because refacto PR is already merged but just: `throw error` then?

2024-05-27 13:13 UTC, adamjorge commented on src/components/custom/profile/profile-privacy.tsx
> +    },
I find it strange to wait for the query to complete before showing the switch animation. 
I think you should handle it optimistically: trigger the animation directly when the button is clicked, and if there is an error, show it with a toast notification.

2024-05-27 13:52 UTC, jimmy-martin commented on src/app/api/minters/[id]/route.ts
> +  const minter = await prisma.minter.findFirstOrThrow({ where: { id: Number(id) } })
I thought I could let the prisma query here since it is very small and simple compared to other prisma queries, but I'll move it

2024-05-27 17:53 UTC, jimmy-martin commented on src/lib/query/minters/fetchMinter.ts
> +    const response = await axios.get<Minter>(`/api/minters/${userId.toString()}`)
Yes we'll try to do it like that in new developments

2024-05-27 17:53 UTC, jimmy-martin commented on src/lib/query/minters/fetchMinter.ts
> +    throw new Error(error as string)
As we saw together, we'll refactor this in an other PR

2024-05-27 17:53 UTC, jimmy-martin commented on src/lib/query/minters/fetchToggleSearchability.ts
> +    throw new Error(error as string)
As we saw together, we'll refactor this in an other PR

2024-05-27 20:14 UTC, adamjorge requested changes

2024-05-27 20:14 UTC, adamjorge commented on src/lib/query/minters/fetchToggleSearchability.ts
> +    throw new Error(error as string)
Yes in this ticket: https://instamint-deva.atlassian.net/browse/IN-105

2024-05-27 20:14 UTC, adamjorge commented on src/components/custom/profile/profile-privacy.tsx
> +
isPending or isLoading => Spinner, to not see a false display on first render

2024-05-27 20:14 UTC, adamjorge commented on src/lib/query/minters/fetchMinter.ts
> +    throw new Error(error as string)
Yes in this ticket: https://instamint-deva.atlassian.net/browse/IN-105

2024-05-28 17:28 UTC, adamjorge approved these changes

2024-05-28 17:43 UTC, merged

2024-06-07 09:37 UTC, avetisk commented on src/app/api/minters/[id]/toggle-searchability/route.ts
> +  }
Check with Adam's review.