[IN-69] Setup database infrastructure
adamjorge/instamint pull request #3
Opened 2024-04-06 19:52 UTC by jimmy-martin

Link to this ticket : https://instamint-deva.atlassian.net/browse/IN-69

2024-04-07 19:29 UTC, adamjorge requested changes
Overall, it seems good to me. The database conceptual data model appears to be respected. Just remove the auto-generated commented code at the start of the Prisma schema.

2024-04-07 19:29 UTC, adamjorge commented on prisma/schema.prisma
Remove commented code here

2024-04-08 18:58 UTC, adamjorge approved these changes
Commented code got removed, ok to merge

2024-04-08 18:58 UTC, merged

2024-05-18 15:39 UTC, avetisk commented on prisma/schema.prisma
> +  defaultLanguage     String    @default("fr")
Why not just `language`?

2024-05-18 15:40 UTC, avetisk commented on prisma/schema.prisma
> +  isReported Boolean  @default(false)
By whom? About what?

2024-05-18 15:40 UTC, avetisk commented on prisma/scripts/comment/create-comments.ts
> +export async function createComments(prisma: PrismaClient) {
Should be called seed.

2024-05-18 15:41 UTC, avetisk commented on prisma/seed.ts
> +  await createComments(prisma)
What the use of splitting your seeds?