[IN-25] Change avatar profile picture
adamjorge/instamint pull request #31
Opened 2024-05-27 10:53 UTC by adamjorge

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-25

2024-05-29 17:47 UTC, jimmy-martin requested changes

2024-05-29 17:47 UTC, jimmy-martin commented on locales/en.json
> +    "error": "An error occurred while updating your profile",
Maybe u forgot to add it in other languages ?

2024-05-29 17:47 UTC, jimmy-martin commented on prisma/migrations/20240524131719_avatar_key_field/migration.sql
Why change the column name ? Since it is an url at the end I don't think this is bad to let it like that.

If it's because of the aws denomination, I think it's better not to use the same name, because if you use another provider in the future, “avatarKey” might not be understood.

However, it's not a mandatory change as the code is correct and understandable as it stands actually. It's just a thought. Just don't forget to update code if you decide to change it.

2024-05-29 17:47 UTC, jimmy-martin commented on src/app/api/minters/pfp/route.ts
> +    return Response.json({ error: "AWS S3 bucket URL is missing." }, { status: 400 })
use status code helper instead of magic number

2024-05-29 17:47 UTC, jimmy-martin commented on src/app/api/minters/pfp/route.ts
> +      return Response.json({ error: "File is required." }, { status: 400 })
same here, use status code helper instead of magic number

2024-05-29 17:47 UTC, jimmy-martin commented on .github/workflows/main.yml
update .env.example with the new env variables

2024-05-29 17:47 UTC, jimmy-martin commented on src/validators/schemas/translation/messageSchema.ts
Maybe u forgot to add the error field ?

2024-05-29 17:53 UTC, adamjorge commented on prisma/migrations/20240524131719_avatar_key_field/migration.sql
We do not stock full url anymore but just the key of object stored in s3 bucket 
Code then generate custom temporary url using AWS sdk

2024-05-30 08:50 UTC, adamjorge commented on locales/en.json
> +    "error": "An error occurred while updating your profile",
My bad, added it in other languages

2024-05-30 08:53 UTC, adamjorge commented on src/app/api/minters/pfp/route.ts
> +    return Response.json({ error: "AWS S3 bucket URL is missing." }, { status: 400 })
My bad forgot to use it after first version, updated with status: StatusCode.BAD_REQUEST

2024-05-30 08:54 UTC, adamjorge commented on src/app/api/minters/pfp/route.ts
> +      return Response.json({ error: "File is required." }, { status: 400 })
My bad forgot to use it after first version, updated with status: StatusCode.BAD_REQUEST

2024-05-30 09:04 UTC, adamjorge commented on src/validators/schemas/translation/messageSchema.ts
Updated in: https://github.com/adammehdaoui/instamint/pull/31/commits/2de4de870f1460ff41ce1ce8ce31abb3b25de71e

2024-05-30 17:12 UTC, jimmy-martin approved these changes

2024-05-30 17:12 UTC, merged