[IN-64] Upload an original content as a MINTER
adamjorge/instamint pull request #32
Opened 2024-05-29 22:13 UTC by Prajay-Chaudhary

Linked to this ticket: [https://instamint-deva.atlassian.net/browse/IN-64](url)

2024-06-01 07:26 UTC, jimmy-martin requested changes

2024-06-01 07:26 UTC, jimmy-martin commented on locales/fr.json
> +    "Title": "Conditions de téléchargement de contenu original",
`title` instead of `Title`

2024-06-01 07:26 UTC, jimmy-martin commented on src/app/api/upload-original-content/route.ts
> +    if (file.size > 1 * 1024 * 1024 * 1024) {
use a const to define what this calculation mean

`const MAX_FILE_SIZE = 1 * 1024 * 1024 * 1024` for example

2024-06-01 07:26 UTC, jimmy-martin commented on src/app/api/upload-original-content/route.ts
> +        { status: StatusCodes.LENGTH_REQUIRED }
Not sure this status code is relevant.

According to the documentation :
> The HyperText Transfer Protocol (HTTP) 411 Length Required client error response code indicates that the server refuses to accept the request without a defined [Content-Length](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length) header

So, if you don't have the content-length in header whether the file size is good or not, it's probably not the right status code for this case

2024-06-01 07:26 UTC, jimmy-martin commented on src/components/custom/upload-original-content/form-fields/file-upload.tsx
> +              }}
handler before jsx

see https://github.com/adammehdaoui/instamint/pull/7#discussion_r1605808734

2024-06-01 07:26 UTC, jimmy-martin commented on src/components/custom/upload-original-content/upload-form.tsx
> +  const t = useTranslations("uploadOriginalContent")
no need to use it like that, you can instantiate it without path

```ts
const t = useTranslations()
// ...
toast.success(t("global.successFileUpload"))
// ...
<Button type="submit">
    {t("uploadOriginalContent.uploadContentButton")}
</Button>
```

2024-06-01 07:26 UTC, jimmy-martin commented on src/validators/upload-original-content/upload-content.ts
> +      (file) => file.size > 0 && file.size <= 1 * 1024 * 1024 * 1024,
use the const you made before (`MAX_FILE_SIZE`)

2024-06-01 07:26 UTC, jimmy-martin commented on src/validators/upload-original-content/upload-content.ts
> +      (file) => ["image/png", "image/webp", "audio/ogg", "audio/flac"].includes(file.type),
you can const this array too

2024-06-01 08:03 UTC, jimmy-martin requested changes

2024-06-01 08:03 UTC, jimmy-martin commented on src/app/[locale]/(portal)/upload-original-content/page.tsx
> +export default async function UploadOriginalContent() {
add `Page` at the end of the component as we usually do

2024-06-01 10:12 UTC, Prajay-Chaudhary commented on locales/fr.json
> +    "Title": "Conditions de téléchargement de contenu original",
Typo issue: now fixed.

2024-06-01 10:13 UTC, Prajay-Chaudhary commented on src/app/api/upload-original-content/route.ts
> +    if (file.size > 1 * 1024 * 1024 * 1024) {
My bad that i forgot to defined it as const.

2024-06-01 10:15 UTC, Prajay-Chaudhary commented on src/app/api/upload-original-content/route.ts
> +        { status: StatusCodes.LENGTH_REQUIRED }
I thought this status was for showing the error, as the length must be in between those defined file size. However, i've made it as BAD_REQUEST.

2024-06-01 10:16 UTC, Prajay-Chaudhary commented on src/components/custom/upload-original-content/form-fields/file-upload.tsx
> +              }}
You're right. It's fixed now.

2024-06-01 10:21 UTC, Prajay-Chaudhary commented on src/components/custom/upload-original-content/upload-form.tsx
> +  const t = useTranslations("uploadOriginalContent")
Yes, this could be more redable. I've updated it now. Thanks.

2024-06-01 10:33 UTC, Prajay-Chaudhary commented on src/validators/upload-original-content/upload-content.ts
> +      (file) => file.size > 0 && file.size <= 1 * 1024 * 1024 * 1024,
My apologies, I forgot to define it as a const in a separate file for better code organization. Now it's fixed.

2024-06-01 10:35 UTC, Prajay-Chaudhary commented on src/validators/upload-original-content/upload-content.ts
> +      (file) => ["image/png", "image/webp", "audio/ogg", "audio/flac"].includes(file.type),
Yes, it's better to do like as you said. Now, i've exported this const from a seperate file and then import it here.

2024-06-01 10:45 UTC, Prajay-Chaudhary commented on src/app/[locale]/(portal)/upload-original-content/page.tsx
> +export default async function UploadOriginalContent() {
It's fixed now.

2024-06-01 11:41 UTC, jimmy-martin requested changes

2024-06-01 11:41 UTC, jimmy-martin commented on src/components/custom/upload-original-content/form-fields/file-upload.tsx
> +    }
try to use useCallback here

2024-06-01 12:04 UTC, Prajay-Chaudhary commented on src/components/custom/upload-original-content/form-fields/file-upload.tsx
> +    }
Done.

2024-06-01 16:34 UTC, jimmy-martin approved these changes

2024-06-01 16:35 UTC, merged

2024-06-07 10:09 UTC, avetisk commented on src/lib/aws/upload-original-content/uploadFileToS3.ts
> +  }
```ts
// Outside of the function
const typeMap = {
  png: "image/png",
  webp: "image/webp",
  // ...
} as const
const DEFAULT_TYPE = "application/octect-stream"

// inside the function
const type = typeMap[extension] || DEFAULT_TYPE