[IN-31] Like/Dislike an NFT (Part 1)
adamjorge/instamint pull request #33
Opened 2024-06-01 11:47 UTC by jimmy-martin

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-31

NB: notifications will be set up in part 2

2024-06-03 19:44 UTC, adamjorge requested changes

2024-06-03 19:44 UTC, adamjorge commented on prisma/schema.prisma
> +  likedBy           Minter[]        @relation("likes")
It will result in creating a new Likes table, right?

2024-06-03 19:44 UTC, adamjorge commented on src/app/api/nfts/[id]/[action]/route.ts
> +    const isLiked = await handleNftLikeAction(
I'm wonder if the logic is good here since:
dislike => remove a line from Likes table (then it's a DELETE endpoint)
like => add a line to Likes table (then it's a POST endpoint)

I don't know if I understand this well I just wan't to clarify that point

2024-06-03 19:44 UTC, adamjorge commented on src/components/custom/nfts/nft-search-card.tsx
> +              Price: <span className="font-bold text-lg">${nft.price.toString()}</span>
i18n

2024-06-03 19:44 UTC, adamjorge commented on src/components/custom/nfts/nft-search-card.tsx
> +              <p className="text-sm text-muted-foreground">Location: {nft.location}</p>
i18n

2024-06-03 19:44 UTC, adamjorge commented on src/components/custom/nfts/nft-search-card.tsx
> +  const isLiked = () => nft.likedBy.some((minter) => minter.id === currentMinterId)
Why just don't get a boolean here and pass it as a prop to LikeHeart component?

2024-06-03 19:59 UTC, jimmy-martin commented on prisma/schema.prisma
> +  likedBy           Minter[]        @relation("likes")
yes

2024-06-03 20:02 UTC, jimmy-martin commented on src/components/custom/nfts/nft-search-card.tsx
> +              Price: <span className="font-bold text-lg">${nft.price.toString()}</span>
already a ticket for this (https://instamint-deva.atlassian.net/browse/IN-86)

2024-06-03 20:04 UTC, jimmy-martin commented on src/components/custom/nfts/nft-search-card.tsx
> +              <p className="text-sm text-muted-foreground">Location: {nft.location}</p>
Same, already a ticket for this (https://instamint-deva.atlassian.net/browse/IN-86)
But just to be sure, i'll not translate the location itself only the `Location:` part ?

2024-06-03 20:05 UTC, adamjorge commented on src/components/custom/nfts/nft-search-card.tsx
> +              <p className="text-sm text-muted-foreground">Location: {nft.location}</p>
Yep, otherwise it would be out of scope

2024-06-03 20:08 UTC, jimmy-martin commented on src/components/custom/nfts/nft-search-card.tsx
> +  const isLiked = () => nft.likedBy.some((minter) => minter.id === currentMinterId)
I'm already doing this at line 34 (but in fact i'll convert isLiked function into a pure boolean):

```ts
<LikeHeart isLiked={isLiked()} ... />
```

2024-06-03 20:09 UTC, jimmy-martin commented on src/app/api/nfts/[id]/[action]/route.ts
> +    const isLiked = await handleNftLikeAction(
I think you right, I can adapt my http verbs

2024-06-04 13:45 UTC, adamjorge commented on src/components/custom/nfts/nft-search-card.tsx
> +  const isLiked = () => nft.likedBy.some((minter) => minter.id === currentMinterId)
Understood that but why you're not getting directly the boolean like that:

`const isLiked = nft.likedBy.some(minter => minter.id === currentMinterId);`

Maybe I didn't understand something

2024-06-04 14:06 UTC, jimmy-martin commented on src/components/custom/nfts/nft-search-card.tsx
> +  const isLiked = () => nft.likedBy.some((minter) => minter.id === currentMinterId)
yes that's exactly what I'm going to do

2024-06-05 07:01 UTC, jimmy-martin commented on src/app/api/nfts/[id]/[action]/route.ts
> +    const isLiked = await handleNftLikeAction(
as we saw together to avoid duplicating the code, I'll make a single POST endpoint

2024-06-05 08:28 UTC, adamjorge approved these changes

2024-06-05 08:28 UTC, merged

2024-07-08 07:21 UTC, avetisk commented on src/components/custom/feed/nft-feed-card.tsx
> +  const isLiked = () => nft.likedBy.some((minter) => minter.id === minterId)
Why a function?

2024-07-08 07:23 UTC, avetisk commented on src/components/custom/like/like-heart.tsx
> +  const [liked, setLiked] = useState(isLiked)
If you needed it as function because of the `useState`, then better create the function from the props here, rather than in the parent.

2024-07-08 07:23 UTC, avetisk commented on src/components/custom/minters/minter-search-card.tsx
>            alt={`Minter ${minter.id.toString()}`}
Useless `toString()`.

2024-07-08 07:23 UTC, avetisk commented on src/lib/query/nfts/fetchLikeNft.ts
> +  const { data } = await axios.post<{ isLiked: boolean }>(`/api/nfts/${nftId.toString()}/like`)
Useless `toString()`.