[IN-49] Enable and disable notification by type
adamjorge/instamint pull request #37
Opened 2024-06-05 20:27 UTC by adamjorge

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-49

(need to rebase + some work on front with header + notification preferences population on register)

2024-06-07 12:58 UTC, jimmy-martin requested changes

2024-06-07 12:58 UTC, jimmy-martin commented on locales/en.json
> +    "FOLLOW_REQUEST_ACCEPTED": "A user accepted your follow request"
Why uppercase for the keys ?

2024-06-07 12:58 UTC, jimmy-martin commented on src/components/custom/profile/notifications/notification.tsx
> +  const p = useTranslations("notificationPreferences")
U can instantiate it without path

See: https://github.com/adammehdaoui/instamint/pull/32#discussion_r1623168418

2024-06-07 12:58 UTC, jimmy-martin commented on src/components/custom/header.tsx
> +    queryFn: () => fetchBlockchainData(["BTC", "ETH", "XRP"])
why not use `blockchainSymbolsIndex` constant ?

2024-06-07 12:58 UTC, jimmy-martin commented on src/validators/schemas/blockchainDataSchema.ts
only one `eslint-disable camelcase` necessary

2024-06-07 13:26 UTC, adamjorge commented on locales/en.json
> +    "FOLLOW_REQUEST_ACCEPTED": "A user accepted your follow request"
To use the same enum in database in translation (without it I would need to map an array doing e.g. "LIKE": "like"). "LIKE" is the name I get in notification.tsx, I could change it to lowercase if you want in there.

2024-06-07 14:12 UTC, jimmy-martin commented on locales/en.json
> +    "FOLLOW_REQUEST_ACCEPTED": "A user accepted your follow request"
For the consistency of the translation file, you can lowercase the keys, and update the code in notification-preferences.tsx

```ts
//...
name: preference.type.toLowerCase()
...
```

2024-06-08 15:47 UTC, adamjorge commented on src/components/custom/profile/notifications/notification.tsx
> +  const p = useTranslations("notificationPreferences")
It will be a little bit redondant in some case but I did like: https://github.com/adammehdaoui/instamint/pull/32#discussion_r1623168418

2024-06-08 17:24 UTC, adamjorge commented on src/lib/query/users/signOut.ts
Yes sorry for the server action, I just moved the old one and I will call the API here later

2024-06-08 17:29 UTC, jimmy-martin approved these changes

2024-06-08 17:33 UTC, merged

2024-07-08 07:11 UTC, avetisk commented on src/components/custom/profile/notifications/notification-preferences.tsx
> +      <h2 className="font-bold text-xl">{t("notification")}</h2>
Avoid using hx directly, better inject it if needed: you don't know where the reusable component will be used, and thus you may break your heading hierarchy.