[IN-65] Delete any of my own original content as a MINTER
adamjorge/instamint pull request #42
Opened 2024-06-13 22:51 UTC by Prajay-Chaudhary

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-65

2024-06-14 08:06 UTC, jimmy-martin requested changes

2024-06-14 08:06 UTC, jimmy-martin commented on locales/en.json
> +    "Title": "My Original Contents",
`title` instead of `Title` (update it in schema and other translation files)

2024-06-14 08:06 UTC, jimmy-martin commented on src/components/custom/original-contents/empty-state-message.tsx
> +      You don't have any original content yet. All your original contents will be listed here.
you can translate this

2024-06-14 08:06 UTC, jimmy-martin commented on src/components/custom/original-contents/handle-delete-content.tsx
> +}
The norm in our code base is to use types rather than interfaces, and let them at the end of the component itself, so it's better to keep doing that even if both work.

2024-06-14 08:06 UTC, jimmy-martin commented on src/components/custom/original-contents/my-original-contents.tsx
> +}
Same here, the norm in our code base is to use types rather than interfaces, and let them at the end of the component itself, so it's better to keep doing that even if both work.

2024-06-14 08:06 UTC, jimmy-martin commented on src/components/custom/original-contents/original-content-grid.tsx
> +}
Same here, the norm in our code base is to use types rather than interfaces, and let them at the end of the component itself, so it's better to keep doing that even if both work.

2024-06-14 08:06 UTC, jimmy-martin commented on src/components/custom/original-contents/my-original-contents.tsx
> +  }
unnecessary if sequence

2024-06-14 08:06 UTC, jimmy-martin commented on src/lib/aws/upload-original-content/uploadFileToS3.ts
> +import { createPresignedUrl } from "./createPresignedUrl"
use alias import instead

2024-06-14 08:06 UTC, jimmy-martin commented on src/components/custom/original-contents/original-content-grid.tsx
> +              {formatDistanceToNow(new Date(oc.createdAt), { addSuffix: true })}
You can use next-intl package to do this kind of things, instead of using a new package. You can check the `useRelativetime` hook or the documentation.

2024-06-14 20:21 UTC, Prajay-Chaudhary commented on locales/en.json
> +    "Title": "My Original Contents",
My bad. Corrected now.

2024-06-14 20:22 UTC, Prajay-Chaudhary commented on src/components/custom/original-contents/empty-state-message.tsx
> +      You don't have any original content yet. All your original contents will be listed here.
I forgot to put translation here. Done!

2024-06-14 20:25 UTC, Prajay-Chaudhary commented on src/components/custom/original-contents/handle-delete-content.tsx
> +}
You're right. I've corrected it now.

2024-06-14 20:25 UTC, Prajay-Chaudhary commented on src/components/custom/original-contents/my-original-contents.tsx
> +}
Done.

2024-06-14 20:26 UTC, Prajay-Chaudhary commented on src/components/custom/original-contents/original-content-grid.tsx
> +}
Same here, corrected.

2024-06-14 20:26 UTC, Prajay-Chaudhary commented on src/lib/aws/upload-original-content/uploadFileToS3.ts
> +import { createPresignedUrl } from "./createPresignedUrl"
Done

2024-06-14 20:34 UTC, Prajay-Chaudhary commented on src/components/custom/original-contents/my-original-contents.tsx
> +  }
I've removed if conditions, and now used more straightforward approach with conditional rendering.

2024-06-14 21:41 UTC, Prajay-Chaudhary commented on src/components/custom/original-contents/original-content-grid.tsx
> +              {formatDistanceToNow(new Date(oc.createdAt), { addSuffix: true })}
You're right, now using relative time and i've made it as a seperate resuable component. Thanks!

2024-06-16 15:54 UTC, jimmy-martin requested changes

2024-06-16 15:54 UTC, jimmy-martin commented on src/components/custom/original-contents/my-original-contents.tsx
>  }
move this to the bottom of the file

2024-06-16 15:54 UTC, jimmy-martin commented on src/components/custom/original-contents/original-content-grid.tsx
>  }
Same, move this to the bottom of the file

2024-06-16 15:54 UTC, jimmy-martin commented on src/components/ui/custom/relative-time-formatter.tsx
why create a component for this instead of a function to call (maybe the `useRelativeTime` hook which is already created can be used)

2024-06-16 19:58 UTC, Prajay-Chaudhary commented on src/components/ui/custom/relative-time-formatter.tsx
yes! As we already have that hook, i've refactored the component to use it.

2024-06-16 19:58 UTC, Prajay-Chaudhary commented on src/components/custom/original-contents/original-content-grid.tsx
>  }
Done

2024-06-16 19:58 UTC, Prajay-Chaudhary commented on src/components/custom/original-contents/my-original-contents.tsx
>  }
Done

2024-06-17 17:40 UTC, jimmy-martin approved these changes

2024-06-17 17:41 UTC, merged

2024-07-08 07:30 UTC, avetisk commented on src/components/custom/original-contents/my-original-contents.tsx
> +  )
You can use IFEE in such cases:

```ts
return (
 <div className="m-1">
    <div className="my-5">
      <h3 className="text-center text-4xl mt-3 font-bold">{t("title")}</h3>
    </div>
    {(() => {
      if (isPending) {
        return (
          <div className="flex justify-center items-center h-10">
            <Spinner />
          </div>
        )
      }
  
      return contents.length === 0
        ? <EmptyStateMessage />
        : <OriginalContentGrid contents={contents} onDelete={handleContentDelete} />
    })()}
  </div>
)
```

Or even, exceptionally, as it's JSX, nested ternaries:

```ts
return (
  <div className="m-1">
    <div className="my-5">
      <h3 className="text-center text-4xl mt-3 font-bold">{t("title")}</h3>
    </div>
    {
      isPending
        ? (
          <div className="flex justify-center items-center h-10">
            <Spinner />
          </div>
        )
        : (
          contents.length === 0
            ? <EmptyStateMessage />
            : <OriginalContentGrid contents={contents} onDelete={handleContentDelete} />
        )
    }
  </div>
)
```