[IN-63] Disable MINTER account (backoffice)
adamjorge/instamint pull request #53
Opened 2024-06-19 17:27 UTC by jimmy-martin

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-63

2024-06-20 07:34 UTC, adamjorge requested changes

2024-06-20 07:34 UTC, adamjorge commented on src/app/api/minters/[id]/disable/route.ts
> +  await disableMinter(id)
Any reason why you don't wan't to catch the error to return a custom error message from the API?

2024-06-20 07:34 UTC, adamjorge commented on src/app/api/minters/[id]/route.ts
> +    return new Response(null, { status: StatusCodes.FORBIDDEN })
I'm not a fan of returning null as a body since we're not doing like that in the rest of the app, maybe try to custom it (using ReasonPhrases enum or a custom API enum?)

2024-06-20 07:34 UTC, adamjorge commented on src/components/custom/admin/minters/minter-actions-button.tsx
> +      mutation.mutate(minterId)
I find it weird to describe the mutation in the parent component and using it in a function in child component?
I don't understand why you're not defining it here (or you could define handleClick in parent and pass it to the component as prop? idk)

2024-06-20 07:34 UTC, adamjorge commented on src/components/custom/sign-in/sign-in-wrapper.tsx
> +
it's too much different compared to the others displays (invalidCredentials and deletedAccount) imo

2024-06-20 07:34 UTC, adamjorge commented on src/constants/userNotActivated.ts
> +export const USER_NOT_ACTIVATED = "user_not_activated"
hmmmm, maybe try to use an object with as const with the others possibilities of error

2024-06-20 17:36 UTC, jimmy-martin commented on src/components/custom/admin/minters/minter-actions-button.tsx
> +      mutation.mutate(minterId)
As the mutations are actually in a hook (u can simply manage mutations in it) , I think it's more flexible to do it like that and keep this component agnostic. And for the possibility to pass the handler directly I do it like that since the parent component started to be huge.

2024-06-20 17:42 UTC, jimmy-martin commented on src/app/api/minters/[id]/disable/route.ts
> +  await disableMinter(id)
As most of the time we don't use the error from the API (the error is generic from the translation files), and it's catched in the front part. So I prefer not do it here.

2024-06-21 08:18 UTC, jimmy-martin commented on src/components/custom/sign-in/sign-in-wrapper.tsx
> +
as we saw together, I'll let this part like this (juste update the const in src/hooks/useMinterActions.ts) and I'll manage use the NextAuth default error like that too to keep the code consistent

2024-06-21 15:17 UTC, adamjorge reviewed
Ok to merge just waiting for e2e step to be success

2024-06-22 14:56 UTC, adamjorge approved these changes

2024-06-22 14:57 UTC, merged