[IN-35] Share a link to a specific NFT as a MINTER
adamjorge/instamint pull request #55
Opened 2024-06-19 21:20 UTC by Prajay-Chaudhary

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-35

2024-06-20 04:24 UTC, jimmy-martin requested changes
As it is a share button, maybe you can add one inside an NFT page and in search NFT card too (or you can create a ticket to do it after if you have more important things to develop for presentation).

2024-06-20 04:24 UTC, jimmy-martin commented on src/components/custom/feed/share-specific-nft-link/share-button.tsx
> +        toast.success(t("errorCopyMessage"))
as it is an error, why do you use `toast.success` ?

2024-06-20 04:24 UTC, jimmy-martin commented on src/components/custom/feed/share-specific-nft-link/share-button.tsx
> +  const handleShareClick = () => {
For handlers we use to use `useCallback`

2024-06-20 05:37 UTC, Prajay-Chaudhary commented on src/components/custom/feed/share-specific-nft-link/share-button.tsx
> +        toast.success(t("errorCopyMessage"))
My bad.

2024-06-20 19:57 UTC, Prajay-Chaudhary commented on src/components/custom/feed/share-specific-nft-link/share-button.tsx
> +  const handleShareClick = () => {
Yes, you're right. I totally forgot to use it.

2024-06-20 20:13 UTC, Prajay-Chaudhary commented
> As it is a share button, maybe you can add one inside an NFT page and in search NFT card too (or you can create a ticket to do it after if you have more important things to develop for presentation).

Done. Since it's just about adding the existing component inside an NFT page and in search NFT card, we don't need a new PR to do  it.

2024-06-20 20:14 UTC, Prajay-Chaudhary commented on src/components/custom/feed/share-specific-nft-link/share-button.tsx
> +        toast.success(t("errorCopyMessage"))
Corrected.

2024-06-21 08:28 UTC, jimmy-martin approved these changes

2024-06-21 08:28 UTC, merged