[IN-105] Refactor and enhance source code
adamjorge/instamint pull request #57
Opened 2024-06-24 19:26 UTC by adamjorge

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-105

- [x] Deleting session from database (including migration) 
- [x] Declaring handler outside jsx
- [x] Removed useless fragments
- [x] withErrorHandling api route wrapper
- [x] Usage of map instead of forEach in some prisma queries
- [x] Separation of prisma (server) and axios (client) logic
- [x] Axios client instance
- [x] Removed useless catch
- [x] Added timestamp for follow entity
- [x] Enhance global UI (error message, success message, padding, ...)

2024-06-24 20:17 UTC, jimmy-martin requested changes

2024-06-24 20:17 UTC, jimmy-martin commented on src/components/custom/minters/minter-wrapper.tsx
> +    followMutation.mutate()
maybe a ternary possible here?

2024-06-25 10:08 UTC, adamjorge commented on src/components/custom/minters/minter-wrapper.tsx
> +    followMutation.mutate()
You can't call a function and don't use his return value in a ternary expression (not allowed by the linter)

2024-06-25 20:34 UTC, jimmy-martin approved these changes

2024-06-25 20:34 UTC, merged