[IN-59] List reports (backoffice)
adamjorge/instamint pull request #6
Opened 2024-04-11 10:51 UTC by adamjorge

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-59

Summary of the PR:

- Back office setup (starting with '/admin')
- Prisma schema change to accommodate content in the report
- API route for reports (based on type: minter, tea-bag, or comment)
- Frontend with report cards (including rendering tests)

To-do after this PR:

- Link the 'Check' button in the frontend to a link in the main application
- E2E tests after the authentification for users and admins is set up

2024-04-11 17:50 UTC, jimmy-martin commented on package.json
> +    "build": "prisma generate && next build",
why prisma generate here ?

2024-04-11 18:54 UTC, jimmy-martin commented on src/app/admin/reports/[type]/page.tsx
> +    queryKey: ["reports"],
to better manage the cache, you should also put the type in the cache key

2024-04-11 18:56 UTC, jimmy-martin commented on src/app/admin/reports/[type]/page.tsx
> +      })
set the function apart (maybe in lib folder) and add the type as a parameter

2024-04-11 18:58 UTC, jimmy-martin commented on src/app/api/reports/[type]/route.ts
> +}
you can set this function apart too

2024-04-11 19:40 UTC, jimmy-martin commented on src/app/admin/reports/[type]/page.tsx
> +    queryKey: ["reports"],
https://tanstack.com/query/latest/docs/framework/react/guides/query-keys#if-your-query-function-depends-on-a-variable-include-it-in-your-query-key

2024-04-11 19:49 UTC, jimmy-martin commented on src/app/api/reports/[type]/route.ts
> +}
and cut your different returns into small functions

2024-04-11 20:06 UTC, jimmy-martin commented on src/validators/types/report.ts
> +export type Report = "minters" | "comments" | "teabags"
change the name of the variable to `ReportType`

2024-04-11 20:07 UTC, jimmy-martin requested changes
Recreate the Makefile and it's ok

2024-04-11 20:30 UTC, adamjorge commented on package.json
> +    "build": "prisma generate && next build",
Because of this error while deploying in preview mode: https://github.com/adammehdaoui/instamint/actions/runs/8619816582/job/23625380516
You need to generate the prisma client in the build process

2024-04-11 20:30 UTC, adamjorge commented on src/app/admin/reports/[type]/page.tsx
> +    queryKey: ["reports"],
Added type dependency to useQuery: queryKey: ["reports", type],

2024-04-11 20:34 UTC, adamjorge commented on src/app/admin/reports/[type]/page.tsx
> +      })
Moved the function to /lib/query/reports/fetchReports.ts
All other query functions (fetch and call of API) will be in query folder with prisma init in /lib

2024-04-11 20:37 UTC, adamjorge commented on src/app/api/reports/[type]/route.ts
> +}
I refactored it in /lib/query/reports/getReports.ts

2024-04-11 20:37 UTC, adamjorge commented on src/validators/types/report.ts
> +export type Report = "minters" | "comments" | "teabags"
Report -> ReportType

2024-04-11 20:50 UTC, jimmy-martin approved these changes

2024-04-11 20:50 UTC, merged

2024-05-11 09:02 UTC, avetisk commented on prisma/schema.prisma
> +  id                Int             @id @default(autoincrement())
In case of a large database scaled worldwide, it's better to use UUIDs.

Also, UUID avoid scrapping by providing non-incremental IDs.

It's OK for the project, but keep it in mind when you will have to deal with such a case.

2024-05-11 18:54 UTC, avetisk commented on src/validators/schemas/reportSchema.ts
> +export const ReportsValidationSchema = z.array(ReportValidationSchema)
This approach may come unhandy as it will differ in terms of required/optional fields.

Compare validation on frontend form VS API POST vs API PATCH.

It's better to create field validators than aggregated ones.

2024-06-25 08:14 UTC, adamjorge commented on src/validators/schemas/reportSchema.ts
> +export const ReportsValidationSchema = z.array(ReportValidationSchema)
used Array.from to convert the Set to Array 

`const deletionMintersPromises = Array.from(mintersToDelete).map((minterId) =>
    prisma.minter.delete({
      where: {
        id: minterId
      }
    })
  )
`