[IN-27] Search NFTs
adamjorge/instamint pull request #7
Opened 2024-04-14 06:51 UTC by jimmy-martin

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-27

2024-04-14 16:46 UTC, adamjorge requested changes
I will also use the types folder to store my Zod types.

Summary of the review : 

- Request -> NextRequest and NextResponse ?
- React Suspense -> loading.tsx
- Move all types to the 'types' folder
- Conceptual Database Model interrogations

2024-04-14 16:46 UTC, adamjorge commented on package.json
> +    "http-status-codes": "^2.3.0",
I'm wondering why you're not using NextRequest and NextResponse.

2024-04-14 16:46 UTC, adamjorge commented on src/app/search/page.tsx
Maybe try using Next's loading API. It does the same thing and it's enough for what you're doing (basically the same thing): 
https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming

"In the same folder, loading.js will be nested inside layout.js. It will automatically wrap the page.js file and any children below in a <Suspense> boundary." -> automatic

Or only use the isPending object of TanstackQuery.

After that move the content of the SearchPage component here.

2024-04-14 16:46 UTC, adamjorge commented on src/components/custom/nfts/nft-card.tsx
> +        <CardTitle className="text-xl">@{nft.originalContent?.minter?.username}</CardTitle>
I'm wondering in which case a Minter can create an NFT without original content.

2024-04-14 16:46 UTC, adamjorge commented on src/components/custom/search/search-drawer.tsx
> +import { Button } from "../../ui/button"
Consider using aliases here, it would be better for us when refactoring the app.

2024-04-14 16:46 UTC, adamjorge commented on src/components/custom/search/search-drawer.tsx
> +        <DrawerFooter>
Add margin top the cancel button component.

2024-04-14 16:46 UTC, adamjorge commented on src/components/custom/search/search-drawer.tsx
> +  const handleSearchSubmit = () => {
Wrap each function (handleSearchSubmit) in a useCallback React hook

2024-04-14 16:46 UTC, adamjorge commented on src/components/custom/search/search-page.tsx
> +    queryFn: () => fetchNfts(search as string)
To avoid doing this (as string), try use a component with search treatment logic which wraps querying and fetching logic.

2024-04-14 16:46 UTC, adamjorge commented on src/components/footer/index.tsx
> +import { Drawer, DrawerTrigger } from "../ui/drawer"
Same as before, try to use aliases import here.

2024-04-14 16:46 UTC, adamjorge commented on src/validators/schemas/hashtagSchema.ts
> +  createdAt: z.string().optional()
We shouldn't have the possibility to have hashtag without creation date ? 
Try changing the seed.

2024-04-14 16:46 UTC, adamjorge commented on src/validators/schemas/originalContent.ts
> +  createdAt: z.string().nullable().optional(),
Same as before why we authorize optional creation date ?

2024-04-14 16:46 UTC, adamjorge commented on src/validators/schemas/searchSchema.ts
In my opinion it would be better to move the type in the "types" folder.

2024-04-14 16:46 UTC, adamjorge commented on __tests__/search/search.test.tsx
> +      // Images are lazy loaded, so we need to wait for the image to load
Remove commented code here (sorry 😅)

2024-04-14 16:46 UTC, adamjorge commented on src/validators/schemas/minterSchema.ts
> +export type MinterSchemaType = z.infer<typeof minterSchema>
Move this to the types folder.

2024-04-14 16:46 UTC, adamjorge commented on src/validators/schemas/nftSchema.ts
> +export type NftSchemaType = z.infer<typeof nftSchema>
Move this to the types folder.

2024-04-14 16:46 UTC, adamjorge commented on src/components/custom/search/search-page.tsx
> +  if (!data || data.length === 0) {
Use the error boolean tanstack object to test if the query failed (if(error) after that).

And replace the current line with this :

if(!data.length)

2024-04-14 16:46 UTC, adamjorge commented on src/components/custom/search/search-page.tsx
> +    <div>
Center content and add margin top (for better basic display).

2024-04-14 18:20 UTC, jimmy-martin commented on __tests__/search/search.test.tsx
> +      // Images are lazy loaded, so we need to wait for the image to load
IMOP its a necessary comment but i'll remove it xD

2024-04-14 18:24 UTC, jimmy-martin commented on package.json
> +    "http-status-codes": "^2.3.0",
I'll use NextResponse and/or NextRequest if necessary, if not i'll use native Response/Request object

2024-04-14 18:28 UTC, jimmy-martin commented on src/components/custom/nfts/nft-card.tsx
> +        <CardTitle className="text-xl">@{nft.originalContent?.minter?.username}</CardTitle>
I'll refactor this and create specific schema for search

2024-04-14 18:29 UTC, jimmy-martin commented on src/validators/schemas/hashtagSchema.ts
> +  createdAt: z.string().optional()
Again I'll refactor this and create specific schema for search

2024-04-14 18:32 UTC, jimmy-martin commented on src/validators/schemas/minterSchema.ts
> +export type MinterSchemaType = z.infer<typeof minterSchema>
As we saw together, I'll keep the type below the schema as it is correlated.
If it gets weird, it's easy enough to switch to a separate file afterwards.

2024-04-14 18:32 UTC, jimmy-martin commented on src/validators/schemas/nftSchema.ts
> +export type NftSchemaType = z.infer<typeof nftSchema>
Again, as we saw together, I'll keep the type below the schema as it is correlated.
If it gets weird, it's easy enough to switch to a separate file afterwards.

2024-04-14 18:33 UTC, jimmy-martin commented on src/validators/schemas/originalContent.ts
> +  createdAt: z.string().nullable().optional(),
Again I'll refactor this and create specific schema for search

2024-04-14 18:33 UTC, jimmy-martin commented on src/validators/schemas/searchSchema.ts
Again, as we saw together, I'll keep the type below the schema as it is correlated.
If it gets weird, it's easy enough to switch to a separate file afterwards.

2024-04-15 19:39 UTC, jimmy-martin commented on src/components/custom/search/search-page.tsx
> +    queryFn: () => fetchNfts(search as string)
Instead, I managed null value in `fetchNfts` function

2024-04-15 20:03 UTC, adamjorge requested changes
All conversations are resolved.
Just center Loading component and ok to merge.

2024-04-15 20:03 UTC, adamjorge commented on src/app/search/loading.tsx
Center it for basic display (will update to spinner)

2024-04-15 20:14 UTC, adamjorge approved these changes
All changes are addressed

2024-04-15 20:14 UTC, merged

2024-05-18 15:44 UTC, avetisk commented on src/app/api/nfts/route.ts
> +  }
Why do you need the search param?

The REST endpoint should require such param as mandatory.

2024-05-18 15:45 UTC, avetisk commented on src/components/custom/search/search-drawer.tsx
> +            }}
Handlers before JSX.

2024-05-18 15:48 UTC, avetisk commented on src/lib/query/nfts/search.ts
> +}
Bad (and dangerous) practice of mixing front and backend code in same file.

2024-05-18 15:51 UTC, avetisk commented on src/lib/query/nfts/search.ts
> +    return searchNftsSchema.parse(res.data.nfts)
Why would do this on the frontend side???

2024-05-18 15:53 UTC, avetisk commented on src/validators/schemas/search/searchSchema.ts
> +export type SearchSchemaType = z.infer<typeof searchSchema>
Don't create code that is only used in a test.