[IN-61] Delete a comment (backoffice)
adamjorge/instamint pull request #8
Opened 2024-04-15 16:50 UTC by adamjorge

Linked to this ticket: [https://instamint-deva.atlassian.net/browse/IN-61](https://instamint-deva.atlassian.net/browse/IN-61)

Summary of the PR:

- Delete a comment feature
- List comments
- Implemented pagination for comments

Additional modifications:

- Fixed the splash screen fix for the PWA
- Changes to the app structure (main app starting with '/portal' and backoffice with '/admin'). A middleware is redirecting '/' to '/portal' 
- Optimizations

2024-04-18 19:19 UTC, jimmy-martin requested changes

2024-04-18 19:19 UTC, jimmy-martin commented on package.json
> +    "lint": "next lint --dir src",
why this change ?
`next lint` command is already linting src

https://nextjs.org/docs/pages/building-your-application/configuring/eslint#linting-custom-directories-and-files

2024-04-18 19:19 UTC, jimmy-martin commented on src/app/api/comments/delete/[id]/route.ts
this endpoint is not REST compliant, you should have the same path for all basic CRUD operations

2024-04-18 19:19 UTC, jimmy-martin commented on src/app/api/comments/delete/[id]/route.ts
> +    await deleteComment(parseInt(id, 10))
if you want to parse the number it could be better to do it internally to avoid to parse every time you call this function, unless it's only here that parsing is needed

2024-04-18 19:19 UTC, jimmy-martin commented on src/lib/query/comments/fetchComments.ts
> +      })
it's better to do it inside the view if we need the full value in other cases

2024-04-18 19:28 UTC, adamjorge commented on package.json
> +    "lint": "next lint --dir src",
I can perform a rollback, but I explicitly specify the directory due to the issue I found :

https://github.com/vercel/next.js/issues/38533

2024-04-18 19:40 UTC, jimmy-martin commented on package.json
> +    "lint": "next lint --dir src",
as you can see here this is merged, so the entire src folder is already linted, no need to add this in the `next lint` command
https://github.com/vercel/next.js/pull/38810/files

2024-04-18 20:00 UTC, adamjorge commented on src/lib/query/comments/fetchComments.ts
> +      })
I now handle format in columns.tsx using ReactTable format

2024-04-18 20:19 UTC, adamjorge commented on src/app/api/comments/delete/[id]/route.ts
Moved delete route to /api/comments/[id]/route.ts

2024-04-18 20:30 UTC, adamjorge commented on src/app/api/comments/delete/[id]/route.ts
> +    await deleteComment(parseInt(id, 10))
I don't understand. Do I need to parse the string parameter every time ? IMO it's the same situation if I do it in deleteComments or in the delete route ? Please provide me with more information

2024-04-18 20:50 UTC, jimmy-martin commented on src/app/api/comments/delete/[id]/route.ts
> +    await deleteComment(parseInt(id, 10))
For example, if I wanted to call the `deleteComment` function anywhere else in the code later, I'd have to use `parseInt` again, so instead I'd prefer to parse inside `deleteComment` to avoid doing so every time I call the function.

2024-04-19 10:16 UTC, jimmy-martin approved these changes

2024-04-19 10:21 UTC, merged

2024-05-11 18:55 UTC, avetisk commented on src/components/custom/comments/actions.tsx
> +          <span className="sr-only">Open menu</span>
i18n.

2024-05-11 18:55 UTC, avetisk commented on src/components/custom/comments/actions.tsx
> +            }}
Handlers must be declared before being used in JSX.

2024-05-11 18:58 UTC, avetisk commented on src/components/custom/comments/comments-table.tsx
> +  })
`react-table` is useless in this case because most features are made for in place sorting/filtering.

In your case you need to do that on the server by making new API calls with updated filter/sorting values.

2024-05-11 18:58 UTC, avetisk commented on src/components/custom/comments/pagination/pagination-ellipsis.tsx
> +    <>
Useless fragment.

2024-05-11 18:59 UTC, avetisk commented on src/components/custom/comments/pagination/pagination-numbers.tsx
> +              setPage(page)
Handlers before JSX.

2024-05-11 18:59 UTC, avetisk commented on src/lib/query/comments/countComments.ts
> +  return await prisma.comment.count()
`await` is useless in this case.

2024-05-11 19:00 UTC, avetisk commented on src/lib/query/comments/fetchComments.ts
> +      throw new Error(err as string)
You can just `throw err` in this case.

2024-05-11 19:00 UTC, avetisk commented on src/lib/query/comments/fetchComments.ts
> +      }
Why?

2024-05-24 16:11 UTC, adamjorge commented on src/components/custom/comments/actions.tsx
> +          <span className="sr-only">Open menu</span>
As a MINTER, I can change the app's interface language => We don't provide i18n for the backoffice for now, only for the main app