[IN-28] Search users and TEA BAGS
adamjorge/instamint pull request #9
Opened 2024-04-16 16:29 UTC by jimmy-martin

Linked to this ticket: https://instamint-deva.atlassian.net/browse/IN-28

2024-04-16 19:40 UTC, adamjorge requested changes

2024-04-16 19:40 UTC, adamjorge commented on src/app/api/teabags/route.ts
Maybe you should refactor API routes for tea bags and minters to use the same route.
For example the path of the route would be '/api/search/[type]'

2024-04-16 19:40 UTC, adamjorge commented on src/components/custom/minters/minter-list.tsx
> +import MinterCard from "./minter-card"
Consider using alias import here

2024-04-16 19:40 UTC, adamjorge commented on src/components/custom/minters/minter-list.tsx
> +      {minters.length === 0 ? (
Optional change: minters.length === 0 to !minters.length

2024-04-16 19:40 UTC, adamjorge commented on src/components/custom/nfts/nft-list.tsx
> +      {nfts.length === 0 ? (
Optional change: nfts.length === 0 to !nfts.length

2024-04-16 19:40 UTC, adamjorge commented on src/components/custom/nfts/nft-list.tsx
> +import NftCard from "./nft-card"
Consider using alias import here

2024-04-16 19:40 UTC, adamjorge commented on src/components/custom/search/search-results.tsx
> +import TeaBagList from "../teabags/teabag-list"
Consider using alias imports here

2024-04-16 19:40 UTC, adamjorge commented on src/components/custom/teabags/teabag-list.tsx
> +import TeaBagCard from "./teabag-card"
Consider using alias import here

2024-04-16 19:40 UTC, adamjorge commented on src/components/custom/teabags/teabag-list.tsx
> +      {teabags.length === 0 ? (
Optional change: teabags.length === 0 to !teabags.length

2024-04-16 19:40 UTC, adamjorge commented on src/lib/query/search/search.ts
> +export async function fetchSearch(searchTerm: string | null) {
I'm wondering why you don't remove the null possibility and create a custom type

2024-04-16 19:40 UTC, adamjorge commented on src/lib/query/nfts/search.ts
> -    const res = await axios.get<SearchSchemaType>(`/api/nfts?search=${searchTerm}`)
Just to confirm, you moved all the search logic to '/search/search.ts'. Are you also testing the type of the searched object here?

2024-04-16 20:27 UTC, jimmy-martin commented on src/components/custom/minters/minter-list.tsx
> +      {minters.length === 0 ? (
I know `!minters.length` is the same, but IMOP even if `minters.length === 0` is more verbose, it's more readable as it describe my intention clearly. For `!minters.length` i have to know that `length` does not exists if an array is empty.

2024-04-16 21:45 UTC, jimmy-martin commented on src/lib/query/search/search.ts
> +export async function fetchSearch(searchTerm: string | null) {
As we saw together, I put searchTerm default value to `""` so that I dont need to check if searchTerm is null but if it is empty right now

2024-04-16 21:47 UTC, jimmy-martin commented on src/lib/query/nfts/search.ts
> -    const res = await axios.get<SearchSchemaType>(`/api/nfts?search=${searchTerm}`)
Yes I'm testing here in https://github.com/adammehdaoui/instamint/pull/9/files/495205009b7833431d1ba07cdb42eaee15dde802#diff-ce078ce27a241e8cd907b490fa5797f764b2612717e010dfebee515061d90207R28-R32 at line 21

```ts
return searchSchema.parse({
  nfts: nfts.data,
  minters: minters.data,
  teabags: teabags.data
})
```

2024-04-17 19:39 UTC, jimmy-martin reviewed
All requested changes are processed

2024-04-17 21:49 UTC, adamjorge requested changes
One little change to address and OK to merge

2024-04-17 21:49 UTC, adamjorge commented on src/lib/query/search/search.ts
> +import { searchNfts } from "../nfts/search"
Use alias import here

2024-04-18 07:39 UTC, adamjorge approved these changes

2024-04-18 07:39 UTC, merged

2024-05-18 15:53 UTC, avetisk commented on src/app/api/search/[type]/route.ts
> +  if (!["minters", "nfts", "teabags"].includes(type)) {
Move the array into a variable.

2024-05-18 15:53 UTC, avetisk commented on src/app/api/search/[type]/route.ts
> +    return Response.json({ message: "Invalid type" }, { status: StatusCodes.BAD_REQUEST })
Create helpers to keep the code DRY.

2024-05-18 15:55 UTC, avetisk commented on src/validators/schemas/search/nfts/nftSearchHashtagSchema.ts
> +  createdAt: z.string()
Why a string?

2024-05-18 15:55 UTC, avetisk commented on src/validators/schemas/search/nfts/nftSearchNftSchema.ts
> +  createdAt: z.string(),
Why not a date?